### ISSUE TITLE
Please use pinyin_get_pinyin_offset to guess candidates

### ISSUE THREAD

**Issue by epico** [fcitx/fcitx-libpinyin#15]
To guess the candidates not at the beginning of the user input.
Please call pinyin_get_pinyin_offset function first,
then call the pinyin_guess_candidates with the offset.

Like:
pinyin_get_pinyin_offset(instance, cursor, &offset);
pinyin_guess_candidates(instance, offset);

**Comment by wengxt** [comment]
it doesn't really give me the result I want, especially when there's separator.
