### ISSUE TITLE
Please use pinyin_left/right_pinyin_offset to move cursor

### ISSUE THREAD

**Issue by epico** [fcitx/fcitx-libpinyin#16]
To move the cursor by pinyin, please call
pinyin_left/right_pinyin_offset function to get the correct cursor.

Like:
pinyin_get_pinyin_offset(instance, cursor, &offset);
pinyin_get_left_pinyin_offset(instance, offset, &left);

**Comment by wengxt** [comment]
For now fcitx-libpinyin never move cursor by pinyin.
