### ISSUE TITLE
Please use pinyin_get_*_auxiliary_text to show auxiliary text

### ISSUE THREAD

**Issue by epico** [fcitx/fcitx-libpinyin#17]
Please use pinyin_get_*_auxiliary_text functions to show auxiliary text.

Like:
pinyin_get_full_pinyin_auxiliary_text(instance, cursor, &aux_text);
pinyin_get_double_pinyin_auxiliary_text(instance, cursor, &aux_text);
pinyin_get_chewing_auxiliary_text(instance, cursor, &aux_text);

**Comment by wengxt** [comment]
I can't use them. Fcitx doesn't show aux text the same way as you designed.
