### ISSUE TITLE
Plan for Qt5 upgrade?

### ISSUE THREAD

**Issue by felixonmars** [fcitx/fcitx-libpinyin#22]
Arch Linux is phasing out the unmaintained qtwebkit component, is there a plan for fcitx-libpinyin to migrate to qt5-webengine, or probably make it an optional dependency?

**Comment by wengxt** [comment]
it's still qt4 based, what are you talking about?

Also it's probably not going away.
http://lists.qt-project.org/pipermail/development/2016-June/026156.html

**Comment by felixonmars** [comment]
https://www.archlinux.org/todo/phasing-out-qtwebkit/

**Comment by felixonmars** [comment]
Thanks a lot!
