### ISSUE TITLE
Please port to use libpinyin 1.9.91

### ISSUE THREAD

**Issue by epico** [fcitx/fcitx-libpinyin#25]
The libpinyin 1.9.91 tar ball is released, and support 1-3 sentence candidates now.

To use libpinyin 1.9.91, please refer to:
https://github.com/epico/ibus-libpinyin/commit/b6fa9a62daaec6374d352ed5e4066e7b105a92c9

**Comment by wengxt** [comment]
I wonder, if I always call pinyin_guess_sentence after pinyin_choose_candidate, regardless of the candidate type, does that mean I only need to use index 0?

**Comment by epico** [comment]
For most cases, use zero as index is okay.

If you like, you could use pinyin_get_candidate_nbest_index function to get the index
for NBEST_MATCH_CANDIDATE, then use the index to call pinyin_get_sentence
and pinyin_train function.
