### ISSUE TITLE
Keybinding For Switching Between Modern and Traditional

### ISSUE THREAD

**Issue by cwmke** [fcitx/fcitx-libpinyin#30]
Would be nice to be able to set a keybinding like ibus does. Thanks for any consideration.

**Comment by wengxt** [comment]
Not sure what do you mean by modern / traditional?

**Comment by cwmke** [comment]
Sorry, switching between modern and traditional characters or Mainland China vs Taiwan used characters.

**Comment by wengxt** [comment]
It is ctrl shift f by default?...

**Comment by cwmke** [comment]
That was what I was looking for. In the future the ability to customize the keybinding would be great. Thanks for the help!

**Comment by wengxt** [comment]
actually it IS customizable.

It’s just another addon and configuration sits in its own place.
