### ISSUE TITLE
After importing the thesaurus, the input method is slow.

### ISSUE THREAD

**Issue by hamkido** [fcitx/fcitx-libpinyin#31]
At the beginning I used a thesaurus(10MB) that I was looking for online, but it was not very suitable for me. Fcitx does not freeze at this time.
Then I made twelve thesaurus. A total of 77Mb. When I imported it, it was very stuttered. I think it's too much and gradually delete the thesaurus. Now there is only one thesaurus, which is 2.7MB in size. But the input method still freezes from time to time.
Restarted and tested several times.
Sometimes fcitx still accidentally takes 100% of the cpu
system detail: debian10

**Comment by wengxt** [comment]
report to libpinyin.
