### ISSUE TITLE
请将fcitx-libpinyin的所有专业词库默认状态设置为关闭

### ISSUE THREAD

**Issue by epico** [fcitx/fcitx-libpinyin#9]
libpinyin 的专业词库是由纯算法生成的，其质量比libpinyin的默认词库要差。
另外，在语言模型的训练过程中，专业词库也是关闭状态。
ibus-libpinyin 已经默认关闭了全部专业词库。

请更新fcitx-libpinyin的专业词库默认状态，谢谢。

**Comment by cherrot** [comment]
如果开启比默认词库质量还要差，那为什么还要展示在词典列表里。。

**Comment by epico** [comment]
所有词库开启会有问题，现在的实现已经影响不大，开启几个词库还是可以的。
